# Generated by Django 5.0.7 on 2024-07-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
