# Generated by Django 5.0.7 on 2024-07-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0002_remove_employee_email_address_remove_employee_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='description_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='painting_name',
        ),
    ]
