# Generated by Django 5.0.7 on 2024-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0003_rename_first_name_employee_description_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=188, upload_to='images'),
            preserve_default=False,
        ),
    ]
